### PR TITLE
Fix web footer

### LINKED ISSUE #113: Fix Mobile Browser Compatibility
In the mobile browser (at least on iPhone8 both Safari and Chrome mobile):

- [ ] the svg in the footer seems to be stretched (probably same issue as https://github.com/Left-on-Read/leftonread/issues/112) 
- [ ] the text animation seems to be cut off slightly

### PR DESCRIPTION
**Pull request by alexdanilowicz**
Resolves #113 and #112

### CODE REVIEW

File: web/src/components/Footer.tsx [hunk 1]
```diff
@@ -25,14 +26,14 @@ export function Footer() {
...
-              width: '100%',
             }}
           >
             <Link href="/">
               <img
                 src={require('../assets/ICON.png')}
                 css={{
-                  width: '64px',
+                  width: '66px',
+                  height: '62.4px',
```
Comment (Teddarific) [inline web/src/components/Footer.tsx:36]: Does a square not work (e.g. width = height)? I think the icon by itself should be a square

Comment (alexdanilowicz) [reply web/src/components/Footer.tsx:36]: No it shouldn't. The logo is 330 by 312, see https://github.com/Left-on-Read/leftonread/blob/main/web/src/assets/ICON.png

66 by 62.4 is 20% of that.
